### ISSUE TITLE
 Problem 1     - Root composer.json requires epubli/epub dev-master -> satisfiable by epubli/epub[dev-master].     - epubli/epub dev-master requires epubli/common master -> could not be found in any version, there may be a typo in the package name.

### ISSUE THREAD

**Issue by kiduyu-klaus** [epubli/epub#2]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires epubli/epub dev-master -> satisfiable by epubli/epub[dev-master].
    - epubli/epub dev-master requires epubli/common master -> could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by l0wskilled** [comment]
This repository is not actively maintained anymore, sorry.
